# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-03 10:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opening', models.TimeField(blank=True)),
                ('close', models.TimeField(blank=True)),
                ('break_start', models.TimeField(blank=True)),
                ('break_close', models.TimeField(blank=True)),
                ('opening_weekend', models.TimeField(blank=True)),
                ('close_weekend', models.TimeField(blank=True)),
                ('break_start_weekend', models.TimeField(blank=True)),
                ('break_close_weekend', models.TimeField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='PersonEmpowered',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('surname', models.CharField(max_length=128)),
                ('phone', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Shopkeeper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax_code', models.CharField(max_length=128)),
                ('shop_name', models.CharField(max_length=512)),
                ('shop_street', models.CharField(max_length=512)),
                ('postal_code', models.CharField(max_length=128)),
                ('country', models.CharField(max_length=128)),
                ('region', models.CharField(max_length=128)),
                ('phone', models.CharField(max_length=128)),
                ('mobile_phone', models.CharField(max_length=128)),
                ('timetable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.Day')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available_shipments', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='SubscriptionType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('days', models.IntegerField(default=0)),
                ('notification', models.BooleanField(default=False)),
                ('amount_of_addresses', models.IntegerField(default=0)),
                ('amount_of_shipments', models.IntegerField(default=0)),
                ('number_of_persons_empowered', models.IntegerField(default=0)),
                ('store_shipment_fee', models.FloatField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='subscription',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.SubscriptionType'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='personempowered',
            name='subscription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.Subscription'),
        ),
    ]
