# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-11 12:29
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0007_auto_20160411_1111'),
    ]

    operations = [
        migrations.CreateModel(
            name='Addresses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shopkeeper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.Shopkeeper')),
            ],
        ),
        migrations.AlterField(
            model_name='subscription',
            name='renew_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 11, 12, 29, 55, 473826)),
        ),
        migrations.AddField(
            model_name='addresses',
            name='subscription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.Subscription'),
        ),
    ]
