# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-11 06:30
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0011_auto_20160510_1313'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcel',
            name='name',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2016, 5, 11, 6, 30, 22, 347073)),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='renew_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 5, 11, 6, 30, 22, 344296)),
        ),
    ]
